name: Generate Snake Animation

on:
  schedule: 
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: sanal-m-s
          color_snake: auto
          color_dots: auto
          color_bg: auto

      - name: Commit and Push
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true
          commit_message: "Generate snake animation"
          publish_dir: /dist
